require('dotenv').config();
const express=require('express'),cors=require('cors'),path=require('path'),app=express();
app.use(cors());app.use(express.json());app.use(express.urlencoded({extended:true}));
app.use('/uploads',express.static(path.join(__dirname,'../uploads')));
app.use(express.static(path.join(__dirname,'../public')));
app.use('/api/auth',require('./routes/auth.routes'));
app.use('/api/surat',require('./routes/surat.routes'));
app.use('/api/admin',require('./routes/admin.routes'));
app.use('/api/jenis-surat',require('./routes/jenis.routes'));
app.use('/api/notifikasi',require('./routes/notifikasi.routes'));
app.use('/api/kontak',require('./routes/kontak.routes'));
app.get('/api/health',(req,res)=>res.json({status:'OK'}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));
app.use((err,req,res,next)=>res.status(500).json({success:false,message:err.message}));
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(`SIPADES running → http://localhost:${PORT}`));
